export const AUDIT_OUTCOMES = ['SUCCESS', 'FAILURE', 'DENIED'] as const;

export type AuditOutcome = typeof AUDIT_OUTCOMES[number];

export const AUDIT_EVENT_TYPES = [
  'LOGIN_STARTED', 'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'SESSION_CREATED', 'SESSION_REVOKED', 'LOGOUT',
  'AUTHENTICATION_DENIED', 'ACCESS_DENIED', 'ACCESS_GRANTED',
] as const;

export type AuditEventType = typeof AUDIT_EVENT_TYPES[number];

export interface AuditEvent {
  eventId: string;
  occurredAt: string;
  eventType: AuditEventType;
  outcome: AuditOutcome;

  actorEmail?: string;
  resource?: string;
  action?: string;

  correlationId: string;
  flowId?: string;

  metadata?: Record<string, string | number | boolean>;
}

// eventId and occurredAt are generated by the AuditTrail implementation, not supplied by the caller.
export type RecordAuditEventInput = Omit<AuditEvent, 'eventId' | 'occurredAt'>;
