export const AUDIT_OUTCOMES = ['SUCCESS', 'FAILURE', 'DENIED'] as const;

export type AuditOutcome = typeof AUDIT_OUTCOMES[number];

export const AUDIT_EVENT_TYPES = [
  'LOGIN_STARTED', 'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'SESSION_CREATED', 'SESSION_REVOKED', 'LOGOUT',
  'AUTHENTICATION_DENIED', 'ACCESS_DENIED', 'ACCESS_GRANTED', 'SPORT_PDF_DOWNLOADED',
  'SPORT_EXCEL_REQUESTED', 'SPORT_EXCEL_DOWNLOADED', 'SPORT_EXCEL_DELETED', 'SPORT_EXCEL_GENERATED', 'SPORT_EXCEL_GENERATION_FAILED',
  'PERMISSION_SUBJECT_CREATED', 'PERMISSION_RESOURCE_ADDED', 'PERMISSION_RESOURCE_CHANGED', 'PERMISSION_RESOURCE_REMOVED',
  'PERMISSION_SUBJECT_REMOVED', 'PERMISSION_CHANGE_DENIED',
  'WOONBEHOEFTE_CASE_CLAIMED', 'WOONBEHOEFTE_CASE_RELEASED', 'WOONBEHOEFTE_CASE_TAKEN_OVER', 'WOONBEHOEFTE_STATUS_CHANGED',
  'WOONBEHOEFTE_ASSESSMENT_UPDATED', 'WOONBEHOEFTE_NOTE_ADDED', 'WOONBEHOEFTE_CHECK_REQUESTED', 'WOONBEHOEFTE_CHECK_COMPLETED',
  'WOONBEHOEFTE_DOCUMENT_DOWNLOADED',
] as const;

export type AuditEventType = typeof AUDIT_EVENT_TYPES[number];

export interface AuditEvent {
  eventId: string;
  occurredAt: string;
  eventType: AuditEventType;
  outcome: AuditOutcome;

  actorEmail?: string;
  // The medewerker a permissionmutatie is about, distinct from actorEmail (who performed it).
  targetEmail?: string;
  resource?: string;
  action?: string;

  correlationId: string;
  flowId?: string;

  metadata?: Record<string, string | number | boolean>;
}

// eventId and occurredAt are generated by the AuditTrail implementation, not supplied by the caller.
export type RecordAuditEventInput = Omit<AuditEvent, 'eventId' | 'occurredAt'>;
