export type AuditOutcome = 'SUCCESS' | 'FAILURE' | 'DENIED';

export interface AuditEvent {
  eventId: string;
  occurredAt: string;
  eventType: string;
  outcome: AuditOutcome;

  actorEmail?: string;
  resource?: string;
  action?: string;

  correlationId: string;
  flowId?: string;

  metadata?: Record<string, string | number | boolean>;
}

// eventId and occurredAt are generated by the AuditTrail implementation, not supplied by the caller.
export type RecordAuditEventInput = Omit<AuditEvent, 'eventId' | 'occurredAt'>;
