// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for WoonbehoefteExcelWorkerFunction
 */
export interface WoonbehoefteExcelWorkerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/app/woonbehoefte/reports/woonbehoefteExcelWorker.
 */
export class WoonbehoefteExcelWorkerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: WoonbehoefteExcelWorkerFunctionProps) {
    super(scope, id, {
      description: 'src/app/woonbehoefte/reports/woonbehoefteExcelWorker.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/app/woonbehoefte/reports/woonbehoefteExcelWorker.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}