// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SportCacheWorkerFunction
 */
export interface SportCacheWorkerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/app/sport/cache/sportCacheWorker.
 */
export class SportCacheWorkerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SportCacheWorkerFunctionProps) {
    super(scope, id, {
      description: 'src/app/sport/cache/sportCacheWorker.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/app/sport/cache/sportCacheWorker.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}