// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for AuthorizerFunction
 */
export interface AuthorizerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/app/authorizer/authorizer.
 */
export class AuthorizerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: AuthorizerFunctionProps) {
    super(scope, id, {
      description: 'src/app/authorizer/authorizer.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/app/authorizer/authorizer.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}